# Generated by Django 3.2.8 on 2021-10-12 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentsailing',
            name='ferry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_sailings', to='ferries.ferry'),
        ),
    ]
