# Generated by Django 3.2.8 on 2021-10-12 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferries', '0002_alter_currentsailing_ferry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroutestop',
            name='terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sailing_stops', to='ferries.terminal'),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminals', to='ferries.city'),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='geo_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminals', to='ferries.geoarea'),
        ),
    ]
