# Generated by Django 3.2.8 on 2021-10-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferries', '0004_rename_travel_route_name_terminal_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=127, unique=True),
        ),
        migrations.AlterField(
            model_name='ferry',
            name='name',
            field=models.CharField(max_length=127, unique=True),
        ),
        migrations.AlterField(
            model_name='geoarea',
            name='name',
            field=models.CharField(max_length=127, unique=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='name',
            field=models.CharField(max_length=127, unique=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
