# Generated by Django 3.2.8 on 2021-10-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferries', '0005_auto_20211015_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=127, unique=True),
        ),
    ]
