# Generated by Django 3.2.8 on 2021-10-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferries', '0006_alter_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoarea',
            name='code',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
