# Generated by Django 3.2.8 on 2021-10-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferries', '0007_alter_geoarea_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentsailing',
            name='status',
            field=models.CharField(choices=[('GOOD', 'On time'), ('MEDI', 'Medical emergency'), ('PEAK', 'Peak travel; Loading max number of vehicles'), ('VHCL', 'Loading as many vehicles as possible'), ('ONGN', 'Earlier loading procedure causing ongoing delay'), ('MECH', 'Mechanical issue causing ongoing delays'), ('DELA', 'Vessel start up delay, departing ASAP'), ('SHIP', 'Loading and unloading multiple ships'), ('CREW', 'Crew member enroute to assist with boarding'), ('CNCL', 'Cancelled'), ('HELP', 'Helping customers')], max_length=4, null=True),
        ),
    ]
