# Generated by Django 3.2.7 on 2021-10-02 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('sort_order', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GeoArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('sort_order', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.route')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('is_additional', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('travel_route_name', models.CharField(max_length=250)),
                ('official_page', models.URLField(null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city')),
                ('geo_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.geoarea')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledSailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('sailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled', to='core.sailing')),
            ],
        ),
        migrations.CreateModel(
            name='RouteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_index', models.PositiveIntegerField()),
                ('conditions_are_tracked', models.BooleanField(default=False)),
                ('length_type', models.CharField(max_length=50)),
                ('limited_availability', models.BooleanField()),
                ('is_bookable', models.BooleanField()),
                ('is_walk_on', models.BooleanField()),
                ('allow_motorcycles', models.BooleanField()),
                ('allow_livestock', models.BooleanField()),
                ('allow_walk_on_options', models.BooleanField()),
                ('allow_additional_passenger_types', models.BooleanField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_set', to='core.route')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_routes', to='core.terminal'),
        ),
        migrations.AddField(
            model_name='route',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_routes', to='core.terminal'),
        ),
        migrations.CreateModel(
            name='Ferry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('official_page', models.URLField(null=True)),
                ('built', models.DateField(null=True)),
                ('car_capacity', models.PositiveIntegerField()),
                ('human_capacity', models.PositiveIntegerField()),
                ('horsepower', models.PositiveIntegerField()),
                ('max_displacement', models.FloatField(verbose_name='Max displacement (t)')),
                ('max_speed', models.FloatField(verbose_name='Max speed (knots)')),
                ('total_length', models.FloatField(verbose_name='Total length (m)')),
                ('services', models.ManyToManyField(related_name='providing_ferrys', to='core.Service')),
            ],
        ),
        migrations.CreateModel(
            name='EnRouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_certain', models.BooleanField()),
                ('is_transfer', models.BooleanField()),
                ('order', models.IntegerField()),
                ('sailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='core.sailing')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.terminal')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentSailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField()),
                ('is_delayed', models.BooleanField()),
                ('status', models.CharField(choices=[('GOOD', 'On time'), ('MEDI', 'Medical emergency'), ('PEAK', 'Peak travel; Loading max number of vehicles'), ('VHCL', 'Loading as many vehicles as possible'), ('ONGN', 'Earlier loading procedure causing ongoing delay'), ('SHIP', 'Loading and unloading multiple ships'), ('CREW', 'Crew member enroute to assist with boarding'), ('CNCL', 'Cancelled'), ('HELP', 'Helping customers')], max_length=4)),
                ('ferry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ferry')),
                ('route_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current', to='core.routeinfo')),
            ],
        ),
    ]
