# Generated by Django 3.2.7 on 2021-10-03 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ferry',
            name='official_page',
        ),
        migrations.AddField(
            model_name='currentsailing',
            name='fetched_time',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currentsailing',
            name='official_url',
            field=models.URLField(default=None, verbose_name='Official URL this was scraped from'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ferry',
            name='fetched_time',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ferry',
            name='official_url',
            field=models.URLField(default=None, verbose_name='Official URL this was scraped from'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sailing',
            name='fetched_time',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sailing',
            name='official_url',
            field=models.URLField(default=None, verbose_name='Official URL this was scraped from'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='terminal',
            name='fetched_time',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='terminal',
            name='official_url',
            field=models.URLField(default=None, verbose_name='Official URL this was scraped from'),
            preserve_default=False,
        ),
    ]
