# Generated by Django 3.2.7 on 2021-09-17 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentsailing',
            name='sailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current', to='core.sailing'),
        ),
        migrations.AlterField(
            model_name='currentsailing',
            name='status',
            field=models.CharField(choices=[('GOOD', 'On time'), ('MEDI', 'Medical emergency'), ('PEAK', 'Peak travel; Loading max number of vehicles'), ('VHCL', 'Loading as many vehicles as possible'), ('ONGN', 'Earlier loading procedure causing ongoing delay'), ('SHIP', 'Loading and unloading multiple ships'), ('CREW', 'Crew member enroute to assist with boarding'), ('CNCL', 'Cancelled'), ('HELP', 'Helping customers')], max_length=4),
        ),
    ]
