# Generated by Django 3.2.7 on 2021-10-03 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211002_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentsailing',
            old_name='official_url',
            new_name='official_page',
        ),
        migrations.RenameField(
            model_name='ferry',
            old_name='official_url',
            new_name='official_page',
        ),
        migrations.RenameField(
            model_name='sailing',
            old_name='official_url',
            new_name='official_page',
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='official_url',
        ),
    ]
