# Generated by Django 3.2.7 on 2021-09-20 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitemap', '0002_auto_20210920_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='index_sitemap',
        ),
    ]
