# Generated by Django 3.2.7 on 2021-09-20 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitemap', '0003_remove_page_index_sitemap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='parent_sitemap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='sitemap.sitemap'),
        ),
    ]
